name: "Build and Publish to GHCR"
description: "Builds the partner-chains-node Docker image and pushes it to GHCR."
inputs:
  sha:
    description: "Commit SHA"
    required: true
  tag:
    description: "Release Tag"
    required: true

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Download partner-chains-node-linux-artifact
      uses: actions/download-artifact@v4
      with:
        name: partner-chains-node-linux-artifact

    - name: Write Dockerfile
      run: |
        cat > Dockerfile <<EOF
        FROM debian:bookworm-slim
        RUN apt-get update && apt-get install -y \\
            ca-certificates \\
            libgcc-s1 \\
            libstdc++6 \\
            libc6 \\
            libssl3 \\
            zlib1g \\
            libgomp1 \\
            && rm -rf /var/lib/apt/lists/*
        RUN useradd -m -u 1000 -U -s /bin/sh -d /substrate substrate \\
            && mkdir -p /data /substrate/.local/share/partner-chains-node \\
            && chown -R substrate:substrate /data /substrate \\
            && ln -s /data /substrate/.local/share/partner-chains-node
        COPY ./partner-chains-node-${{ inputs.tag }}-x86_64-linux /usr/local/bin/partner-chains-node
        RUN chown substrate:substrate /usr/local/bin/partner-chains-node \\
            && chmod +x /usr/local/bin/partner-chains-node
        USER substrate
        EXPOSE 30333 9615 9933 9944
        VOLUME ["/data"]
        ENTRYPOINT ["/usr/local/bin/partner-chains-node"]
        EOF
      shell: bash

    - name: Build Docker Image
      run: |
        docker build -t substrate-node:${{ inputs.sha }} .
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        FORCE_COLOR: 1

    - name: Tag and Push Image to GHCR
      run: |
        repository_name="${GITHUB_REPOSITORY##*/}"
        target_image="ghcr.io/${{ github.repository }}/$repository_name-node"
        commit_sha="${{ inputs.sha }}"
        custom_tag="${{ inputs.tag }}"

        docker tag ghcr-image:latest $target_image:latest
        docker tag ghcr-image:latest $target_image:$commit_sha
        docker tag ghcr-image:latest $target_image:$custom_tag

        docker push $target_image:latest
        docker push $target_image:$commit_sha
        docker push $target_image:$custom_tag
      shell: bash

